$ANSIBLE_VAULT;1.1;AES256
30376638646564366139353930336232663461636438383330363661373961396566653533636439
6239306564646134626139313735613964666263333563650a356532633963353530376466616534
36343064383962643861653437313337613039393438363431353335326433313462383065363466
3462366138303639350a636235666533303365623265626236653736623563326137653062623838
37613639323564306364353439653537313163643264323233386565373939323866653461623334
39663164373466383739646137623730336666303934343733356633346636346335376263353766
34356332346333323034396566346262313564326162373363356566373635363238353332313233
36333037303133383230326163376365613436373735336136316533373566326230353231343134
61316532663033396563643062666266323162633863363635343438336662656234326466653933
32616236386266633566613032653165613431376364313035666632373037373632363734623864
66646563343763376265633934316138306264383237653031383861363938346130383030373030
38646630316236613630633032373833376266613662633731643031343836383862306263393565
62303866383132386564363137353239343861363934613632383364323038386236633431633935
35643265643364656234383865393937616665356631373937353765326266383062626532646531
39373030303535363434373965323539306534393561323365653332313266323266336237396361
66653735316165363061333464373630616665363437303536646263393235313935616164303363
31613162383634383537616162656232623531323863666464333236313138376134393864383236
35623436376130613463663333313331633266353838313864313663663163303766316231356363
333739626436383537373230393666663331
